# Generated by Django 4.1 on 2024-10-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="selected_hotel_facilities",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="booking",
            name="selected_room_facilities",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default="", max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_rooms_needed",
            field=models.IntegerField(default=1),
        ),
    ]
