# Generated by Django 4.1 on 2024-10-10 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_booking_selected_hotel_facilities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="selected_hotel_facilities",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="selected_room_facilities",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="total_rooms_needed",
        ),
    ]
